theme: jekyll-theme-cayman
title: Cratchit
description: A Swedish C++ accounting SIE file based application
url: https://kjelloh.github.io
baseurl: /cratchit
repository: kjelloh/cratchit

collections:
  issues:
    output: true
    render_with_liquid: false
  thinking:
    output: true
    render_with_liquid: false

defaults:
  - scope:
      path: ""
    values:
      render_with_liquid: false