#include "cratchit.h"
#include "cratchit_tea.hpp"
#include "tea/ncurses_head.hpp"
#include "sub.hpp"
#include <iostream>

namespace first {

  // TEA functions now defined in cratchit_tea.hpp/cpp

  // ----------------------------------
  // ----------------------------------

  int main(int argc, char *argv[]) {

    logger::business("first::main sais << Hello >> --------------------------------- ");

    auto runtime_encoding = to_inferred_runtime_encoding();
    auto ncurses_head = std::make_unique<TEA::NCursesHead>(runtime_encoding);
    CratchitRuntime app(init,view,update,std::move(ncurses_head));


    auto result = app.run(argc,argv);

    logger::business("first::main sais >> Bye << -----------------------------------");

    return result;

  }
} // namespace first

// This is a function originally generated by conan when initiating a default exe project
void conan_gen_print_build_properties() {

#ifdef NDEBUG
  std::cout << "build properties:: Hello World Release!\n";
#else
  std::cout << "build properties:: Hello World Debug!\n";
#endif

// ARCHITECTURES
#ifdef _M_X64
  std::cout << "  build properties:: _M_X64 defined\n";
#endif

#ifdef _M_IX86
  std::cout << "  build properties:: _M_IX86 defined\n";
#endif

#ifdef _M_ARM64
  std::cout << "  build properties:: _M_ARM64 defined\n";
#endif

#if __i386__
  std::cout << "  build properties:: __i386__ defined\n";
#endif

#if __x86_64__
  std::cout << "  build properties:: __x86_64__ defined\n";
#endif

#if __aarch64__
  std::cout << "  build properties:: __aarch64__ defined\n";
#endif

// Libstdc++
#if defined _GLIBCXX_USE_CXX11_ABI
  std::cout << "  build properties:: _GLIBCXX_USE_CXX11_ABI "
            << _GLIBCXX_USE_CXX11_ABI << "\n";
#endif

// MSVC runtime
#if defined(_DEBUG)
#if defined(_MT) && defined(_DLL)
  std::cout << "  build properties:: MSVC runtime: MultiThreadedDebugDLL\n";
#elif defined(_MT)
  std::cout << "  build properties:: MSVC runtime: MultiThreadedDebug\n";
#endif
#else
#if defined(_MT) && defined(_DLL)
  std::cout << "  build properties:: MSVC runtime: MultiThreadedDLL\n";
#elif defined(_MT)
  std::cout << "  build properties:: MSVC runtime: MultiThreaded\n";
#endif
#endif

// COMPILER VERSIONS
#if _MSC_VER
  std::cout << "  build properties:: _MSC_VER" << _MSC_VER << "\n";
#endif

#if _MSVC_LANG
  std::cout << "  build properties:: _MSVC_LANG" << _MSVC_LANG << "\n";
#endif

#if __cplusplus
  std::cout << "  build properties:: __cplusplus" << __cplusplus << "\n";
#endif

#if __INTEL_COMPILER
  std::cout << "  build properties:: __INTEL_COMPILER" << __INTEL_COMPILER << "\n";
#endif

#if __GNUC__
  std::cout << "  build properties:: __GNUC__" << __GNUC__ << "\n";
#endif

#if __GNUC_MINOR__
  std::cout << "  build properties:: __GNUC_MINOR__" << __GNUC_MINOR__ << "\n";
#endif

#if __clang_major__
  std::cout << "  build properties:: __clang_major__" << __clang_major__ << "\n";
#endif

#if __clang_minor__
  std::cout << "  build properties:: __clang_minor__" << __clang_minor__ << "\n";
#endif

#if __apple_build_version__
  std::cout << "  build properties:: __apple_build_version__"
            << __apple_build_version__ << "\n";
#endif

  // SUBSYSTEMS

#if __MSYS__
  std::cout << "  build properties:: __MSYS__" << __MSYS__ << "\n";
#endif

#if __MINGW32__
  std::cout << "  build properties:: __MINGW32__" << __MINGW32__ << "\n";
#endif

#if __MINGW64__
  std::cout << "  build properties:: __MINGW64__" << __MINGW64__ << "\n";
#endif

#if __CYGWIN__
  std::cout << "  build properties:: __CYGWIN__" << __CYGWIN__ << "\n";
#endif
}


// This is a function originally generated by conan when initiating a default exe project
void cratchit_print_vector(const std::vector<std::string> &strings) {
  for (std::vector<std::string>::const_iterator it = strings.begin();
       it != strings.end(); ++it) {
    std::cout << "build properties: " << *it << std::endl;
  }
}
